### ISSUE TITLE
Fejl i Python-kode - hjælp

### ISSUE THREAD

**Issue by Fibni** [Dataforsyningen/Qgis-dataforsyningen#9]
[Python fejlmeddelelse i Qgis 3.22.1.txt](https://github.com/Dataforsyningen/Qgis-dataforsyningen/files/7698931/Python.fejlmeddelelse.i.Qgis.3.22.1.txt)
2021-12-12T15:10:10     WARNING    Traceback (most recent call last):
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\df_config.py", line 119, in _handle_services_response
              self._get_qlr_file()
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\df_config.py", line 130, in _get_qlr_file
              self._load_config_from_cached_df_qlr()
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\df_config.py", line 158, in _load_config_from_cached_df_qlr
              self.background_category, self.categories = self.get_df_categories()
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\df_config.py", line 173, in get_df_categories
              groups_with_layers = self.df_qlr_file.get_groups_with_layers()
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\qlr_file.py", line 27, in get_groups_with_layers
              layers = self.get_group_layers(group)
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\qlr_file.py", line 45, in get_group_layers
              service = self.get_maplayer_service(maplayer_node)
              File "C:\Users/Finn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\qlr_file.py", line 75, in get_maplayer_service
              return service
             UnboundLocalError: local variable 'service' referenced before assignment

**Comment by Fibni** [comment]
Solved
